exports.ListData = {
  "basicDetails.age": 1,
  "basicDetails.name": 1,
  "basicDetails.gender": 1,
  "basicDetails.userId": 1,
  "basicDetails.dateOfBirth": 1,
  "basicDetails.timeOfBirth": 1,
  "additionalDetails.currentlyLivingInCountry": 1,
  "additionalDetails.currentlyLivingInState": 1,
  "additionalDetails.currentlyLivingInCity": 1,
  "additionalDetails.diet": 1,
  "additionalDetails.height": 1,
  "additionalDetails.maritalStatus": 1,
  "careerDetails.profession": 1,
  "careerDetails.currentDesignation": 1,
  "selfDetails.userPhotos": 1,
  "selfDetails.profilePicture": 1,
  "selfDetails.profilePictureUrl": 1,
  "familyDetails.caste": 1,
  "familyDetails.community": 1,
  "isEmailSubscribed": 1,
};
