const events = {
    REQUESTSENT : "REQUEST_SENT",
    REQUESTACCEPTDECLINE : "REQUEST_ACCEPT_DECLINE",
    NOTIFICATION : "NOTIFICATION",
    INITIATECHATWITHUSER : "INITIATE_CHAT_WITH_USER",
    ADMINNOTIFICATION : "ADMIN_NOTIFICATION",
    DELETETOKEN : "DELETE_TOKEN_FOR_USER",
    ONBLOCK : "ON_BLOCK",
}

module.exports = {events};