const events = {
    REQUESTSENT : "REQUEST_SENT",
    REQUESTACCEPTDECLINE : "REQUEST_ACCEPT_DECLINE",
    NOTIFICATION : "NOTIFICATION",
    ADMINNOTIFICATION : "ADMIN_NOTIFICATION",
    DELETETOKEN : "DELETE_TOKEN_FOR_USER"
}

module.exports = {events}